// <auto-generated />
namespace PGSs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbsetActor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbsetActor));
        
        string IMigrationMetadata.Id
        {
            get { return "201612211936174_dbsetActor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
